x-postgres-base: &postgres-base
  image: postgis/postgis:15-3.3-alpine
  restart: always
  healthcheck:
    test:
      - CMD-SHELL
      - pg_isready -U postgres
    interval: 10s
    timeout: 5s
    retries: 5

x-app-base: &app-base
  restart: always

services:
  postgres-test:
    profiles: ["test"]
    <<: *postgres-base
    env_file: ".env.local"
    environment:
      - POSTGRES_HOST=postgres-test
      - GUNICORN_WORKERS=1
    networks:
      - test

  app-test:
    profiles: ["test"]
    <<: *app-base
    entrypoint: ./scripts/entrypoint-test.sh
    build:
      context: .
      dockerfile: ./snippets/Dockerfile
      args:
        ENV: test
    env_file: ".env.local"
    environment:
      - POSTGRES_DRIVERNAME=postgresql+asyncpg
      - POSTGRES_HOST=postgres-test
      - GUNICORN_WORKERS=1
    volumes:
      - ./:/code
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - test

  postgres-dev:
    profiles: ["dev"]
    <<: *postgres-base
    env_file: ".env.local"
    environment:
      - POSTGRES_HOST=postgres-dev
      - GUNICORN_WORKERS=4
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - dev

  app-dev:
    profiles: ["dev"]
    <<: *app-base
    build:
      context: .
      dockerfile: ./snippets/Dockerfile
    command:
      bash -c "
        gunicorn snippets.api.server:app --config ./snippets/api/gunicorn_config.py"
    env_file: ".env.local"
    environment:
      - POSTGRES_HOST=postgres-dev
      - GUNICORN_WORKERS=4
    volumes:
      - ./snippets:/snippets
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - dev

volumes:
  pgdata-dev:

networks:
  test:
  dev:
