services:
  postgres:
    profiles: ["dev"]
    image: postgis/postgis:16-3.4-alpine
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: ".env"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres/initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - dev

  app:
    profiles: ["dev"]
    build:
      context: .
    command: >
      bash -c "
        gunicorn snippets.server:app --config ./snippets/gunicorn_config.py"
    env_file: ".env"
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev

volumes:
  pgdata-dev:

networks:
  dev:
